// File generated by Firebase Studio.
// Modifications to this file may be overwritten.
//
// If you need to re-generate this file, follow the manual setup instructions.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for iOS - '
          'you can reconfigure this by following the manual setup instructions.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macOS - '
          'you can reconfigure this by following the manual setup instructions.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for Windows - '
          'you can reconfigure this by following the manual setup instructions.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for Linux - '
          'you can reconfigure this by following the manual setup instructions.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyC6sZ9lh0VBZGL1QqIirLriAkksJChA6bU",
    appId: "1:228086845032:web:2eb98767986154f55db5dd",
    messagingSenderId: "228086845032",
    projectId: "booktalk-city",
    authDomain: "booktalk-city.firebaseapp.com",
    storageBucket: "booktalk-city.firebasestorage.app",
    measurementId: "G-6SN1PL55G1",
  );

  // Android 설정은 잠시 후 추가하겠습니다.
  // 우선 웹과 동일한 값으로 기본 설정을 해둡니다.
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: "AIzaSyC6sZ9lh0VBZGL1QqIirLriAkksJChA6bU",
    appId: "1:228086845032:android:PLACEHOLDER", // 이 부분은 Android 앱 등록 후 변경됩니다.
    messagingSenderId: "228086845032",
    projectId: "booktalk-city",
    storageBucket: "booktalk-city.firebasestorage.app",
  );
}
